#config_version=6

mode:
  start_events: start_high_priority
  stop_events: stop_high_priority
  priority: 200

variable_player:
  shot_burn_b_hit:
    score:
      int: 2001
      block: true

  shot_burn_b_unlit_hit:
    score:
      int: 201
      block: false

  shot_burn_b_lit_hit:
    score:
      int: 21
      block: false
