#config_version=6

config:
  - playfield_rings.yaml

lights:
  l_mini_cab_mini:
    number: exp_playfield-2-1
    type: rgb
    tags: lights_a, lights_cab

  l_mini_cab_left:
    number: exp_playfield-2-2
    type: rgb
    tags: lights_b, lights_cab

  l_mini_cab_right:
    number: exp_playfield-2-3
    type: rgb
    tags: lights_a, lights_cab

  l_pf_1:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_ci, lights_lower_third
  l_pf_2:
    number:
    type: grb
    tags: lights_b, lights_pf, lights_gi, lights_lower_third

  l_pf_x2:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_multipliers

  l_burn_b:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_burn
  l_burn_u:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_burn
  l_burn_r:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_burn
  l_burn_n:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_burn

  # Inlanes and Outlanes
  l_left_outlane:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_lanes, lights_outlanes, lights_lower_third
  l_left_inlane:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_lanes, lights_inlanes, lights_lower_third
  l_right_inlane:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_lanes, lights_inlanes, lights_lower_third
  l_right_outlane:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_lanes, lights_outlanes, lights_lower_third

  l_drain:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_lower_third
